export enum textTypes {
  TITLE_BOLD = 'TITLE_BOLD', //24px
  TITLE_SEMIBOLD = 'TITLE_SEMIBOLD',
  TITLE_MEDIUM = 'TITLE_MEDIUM',
  TITLE_REGULAR = 'TITLE_REGULAR',
  TITLE_LIGHT = 'TITLE_LIGHT',
  SUB_TITLE_BOLD = 'SUB_TITLE_BOLD', //20px
  SUB_TITLE_SEMIBOLD = 'SUB_TITLE_SEMIBOLD',
  SUB_TITLE_MEDIUM = 'SUB_TITLE_MEDIUM',
  SUB_TITLE_REGULAR = 'SUB_TITLE_REGULAR',
  SUB_TITLE_LIGHT = 'SUB_TITLE_LIGHT',
  BUTTON_BOLD = 'BUTTON_BOLD', //18px
  BUTTON_SEMIBOLD = 'BUTTON_SEMIBOLD',
  BUTTON_MEDIUM = 'BUTTON_MEDIUM',
  BUTTON_REGULAR = 'BUTTON_REGULAR',
  BUTTON_LIGHT = 'BUTTON_LIGHT',
  PARAGRAPH_BOLD = 'PARAGRAPH_BOLD', //14px
  PARAGRAPH_SEMIBOLD = 'PARAGRAPH_SEMIBOLD',
  PARAGRAPH_MEDIUM = 'PARAGRAPH_MEDIUM',
  PARAGRAPH_REGULAR = 'PARAGRAPH_REGULAR',
  PARAGRAPH_LIGHT = 'PARAGRAPH_LIGHT',
  PARAGRAPH_SMALL_BOLD = 'PARAGRAPH_SMALL_BOLD', //10px
  PARAGRAPH_SMALL_SEMIBOLD = 'PARAGRAPH_SMALL_SEMIBOLD',
  PARAGRAPH_SMALL_MEDIUM = 'PARAGRAPH_SMALL_MEDIUM',
  PARAGRAPH_SMALL_REGULAR = 'PARAGRAPH_SMALL_REGULAR',
  PARAGRAPH_SMALL_LIGHT = 'PARAGRAPH_SMALL_LIGHT',
}
